//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CF.VRent.Entities.KEMASWSIF_AUTHRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:kemas", ConfigurationName="KEMASWSIF_AUTHRef.WSKemasPortType")]
    public interface WSKemasPortType {
        
        // CODEGEN: Generating message contract since message part namespace (urn:kemas) does not match the default value ()
        [System.ServiceModel.OperationContractAttribute(Action="authByLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ws_auth_response")]
        CF.VRent.Entities.KEMASWSIF_AUTHRef.authByLoginResponse authByLogin(CF.VRent.Entities.KEMASWSIF_AUTHRef.authByLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Error")]
        CF.VRent.Entities.KEMASWSIF_AUTHRef.Error logout(string SessionID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kemas")]
    public partial class WS_Auth_Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private string vNameField;
        
        private string resultField;
        
        private string enabledField;
        
        private string blockedField;
        
        private string changePwdField;
        
        private string allowChangePwdField;
        
        private string sessionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VName {
            get {
                return this.vNameField;
            }
            set {
                this.vNameField = value;
                this.RaisePropertyChanged("VName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("Enabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string Blocked {
            get {
                return this.blockedField;
            }
            set {
                this.blockedField = value;
                this.RaisePropertyChanged("Blocked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=6)]
        public string ChangePwd {
            get {
                return this.changePwdField;
            }
            set {
                this.changePwdField = value;
                this.RaisePropertyChanged("ChangePwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string AllowChangePwd {
            get {
                return this.allowChangePwdField;
            }
            set {
                this.allowChangePwdField = value;
                this.RaisePropertyChanged("AllowChangePwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:kemas")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorJSONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorJSON {
            get {
                return this.errorJSONField;
            }
            set {
                this.errorJSONField = value;
                this.RaisePropertyChanged("ErrorJSON");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authByLogin", WrapperNamespace="urn:kemas", IsWrapped=true)]
    public partial class authByLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:kemas", Order=0)]
        public string User;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:kemas", Order=1)]
        public string Pass;
        
        public authByLoginRequest() {
        }
        
        public authByLoginRequest(string User, string Pass) {
            this.User = User;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authByLoginResponse", WrapperNamespace="urn:kemas", IsWrapped=true)]
    public partial class authByLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public CF.VRent.Entities.KEMASWSIF_AUTHRef.WS_Auth_Response ws_auth_response;
        
        public authByLoginResponse() {
        }
        
        public authByLoginResponse(CF.VRent.Entities.KEMASWSIF_AUTHRef.WS_Auth_Response ws_auth_response) {
            this.ws_auth_response = ws_auth_response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSKemasPortTypeChannel : CF.VRent.Entities.KEMASWSIF_AUTHRef.WSKemasPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSKemasPortTypeClient : System.ServiceModel.ClientBase<CF.VRent.Entities.KEMASWSIF_AUTHRef.WSKemasPortType>, CF.VRent.Entities.KEMASWSIF_AUTHRef.WSKemasPortType {
        
        public WSKemasPortTypeClient() {
        }
        
        public WSKemasPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSKemasPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSKemasPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSKemasPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CF.VRent.Entities.KEMASWSIF_AUTHRef.authByLoginResponse CF.VRent.Entities.KEMASWSIF_AUTHRef.WSKemasPortType.authByLogin(CF.VRent.Entities.KEMASWSIF_AUTHRef.authByLoginRequest request) {
            return base.Channel.authByLogin(request);
        }
        
        public CF.VRent.Entities.KEMASWSIF_AUTHRef.WS_Auth_Response authByLogin(string User, string Pass) {
            CF.VRent.Entities.KEMASWSIF_AUTHRef.authByLoginRequest inValue = new CF.VRent.Entities.KEMASWSIF_AUTHRef.authByLoginRequest();
            inValue.User = User;
            inValue.Pass = Pass;
            CF.VRent.Entities.KEMASWSIF_AUTHRef.authByLoginResponse retVal = ((CF.VRent.Entities.KEMASWSIF_AUTHRef.WSKemasPortType)(this)).authByLogin(inValue);
            return retVal.ws_auth_response;
        }
        
        public CF.VRent.Entities.KEMASWSIF_AUTHRef.Error logout(string SessionID) {
            return base.Channel.logout(SessionID);
        }
    }
}
