//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CF.VRent.Entities.PaymentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentCard", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.DataAccessProxy.Entities")]
    [System.SerializableAttribute()]
    public partial class PaymentCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bank {
            get {
                return this.BankField;
            }
            set {
                if ((object.ReferenceEquals(this.BankField, value) != true)) {
                    this.BankField = value;
                    this.RaisePropertyChanged("Bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CardIdField, value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentExchangeMessage", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.DataAccessProxy.Entities")]
    [System.SerializableAttribute()]
    public partial class PaymentExchangeMessage : CF.VRent.Common.Entities.DBEntity.DBEntityObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeductionPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LastPaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreAuthDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreAuthIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreAuthPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreAuthQueryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreAuthTempOrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealPreAuthPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservedMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RetryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RetryCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardID {
            get {
                return this.CardIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CardIDField, value) != true)) {
                    this.CardIDField = value;
                    this.RaisePropertyChanged("CardID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeductionPrice {
            get {
                return this.DeductionPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.DeductionPriceField, value) != true)) {
                    this.DeductionPriceField = value;
                    this.RaisePropertyChanged("DeductionPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastPaymentID {
            get {
                return this.LastPaymentIDField;
            }
            set {
                if ((this.LastPaymentIDField.Equals(value) != true)) {
                    this.LastPaymentIDField = value;
                    this.RaisePropertyChanged("LastPaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentID {
            get {
                return this.PaymentIDField;
            }
            set {
                if ((this.PaymentIDField.Equals(value) != true)) {
                    this.PaymentIDField = value;
                    this.RaisePropertyChanged("PaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreAuthDateTime {
            get {
                return this.PreAuthDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PreAuthDateTimeField, value) != true)) {
                    this.PreAuthDateTimeField = value;
                    this.RaisePropertyChanged("PreAuthDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreAuthID {
            get {
                return this.PreAuthIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PreAuthIDField, value) != true)) {
                    this.PreAuthIDField = value;
                    this.RaisePropertyChanged("PreAuthID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreAuthPrice {
            get {
                return this.PreAuthPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PreAuthPriceField, value) != true)) {
                    this.PreAuthPriceField = value;
                    this.RaisePropertyChanged("PreAuthPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreAuthQueryID {
            get {
                return this.PreAuthQueryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PreAuthQueryIDField, value) != true)) {
                    this.PreAuthQueryIDField = value;
                    this.RaisePropertyChanged("PreAuthQueryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreAuthTempOrderID {
            get {
                return this.PreAuthTempOrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PreAuthTempOrderIDField, value) != true)) {
                    this.PreAuthTempOrderIDField = value;
                    this.RaisePropertyChanged("PreAuthTempOrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RealPreAuthPrice {
            get {
                return this.RealPreAuthPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.RealPreAuthPriceField, value) != true)) {
                    this.RealPreAuthPriceField = value;
                    this.RaisePropertyChanged("RealPreAuthPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservedMsg {
            get {
                return this.ReservedMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservedMsgField, value) != true)) {
                    this.ReservedMsgField = value;
                    this.RaisePropertyChanged("ReservedMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Retry {
            get {
                return this.RetryField;
            }
            set {
                if ((this.RetryField.Equals(value) != true)) {
                    this.RetryField = value;
                    this.RaisePropertyChanged("Retry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RetryCount {
            get {
                return this.RetryCountField;
            }
            set {
                if ((this.RetryCountField.Equals(value) != true)) {
                    this.RetryCountField = value;
                    this.RaisePropertyChanged("RetryCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsCode {
            get {
                return this.SmsCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsCodeField, value) != true)) {
                    this.SmsCodeField = value;
                    this.RaisePropertyChanged("SmsCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueID {
            get {
                return this.UniqueIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueIDField, value) != true)) {
                    this.UniqueIDField = value;
                    this.RaisePropertyChanged("UniqueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetryBooking", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.DataAccessProxy.Entities")]
    [System.SerializableAttribute()]
    public partial class RetryBooking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeductionPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> NewCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> OldCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CF.VRent.UPSDK.PayOperationEnum OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreAuthPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreAuthQueryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RealPreAuthPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeductionPrice {
            get {
                return this.DeductionPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.DeductionPriceField, value) != true)) {
                    this.DeductionPriceField = value;
                    this.RaisePropertyChanged("DeductionPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> NewCard {
            get {
                return this.NewCardField;
            }
            set {
                if ((this.NewCardField.Equals(value) != true)) {
                    this.NewCardField = value;
                    this.RaisePropertyChanged("NewCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> OldCard {
            get {
                return this.OldCardField;
            }
            set {
                if ((this.OldCardField.Equals(value) != true)) {
                    this.OldCardField = value;
                    this.RaisePropertyChanged("OldCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CF.VRent.UPSDK.PayOperationEnum Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((this.OperationField.Equals(value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderItemId {
            get {
                return this.OrderItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderItemIdField, value) != true)) {
                    this.OrderItemIdField = value;
                    this.RaisePropertyChanged("OrderItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentId {
            get {
                return this.PaymentIdField;
            }
            set {
                if ((this.PaymentIdField.Equals(value) != true)) {
                    this.PaymentIdField = value;
                    this.RaisePropertyChanged("PaymentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreAuthPrice {
            get {
                return this.PreAuthPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PreAuthPriceField, value) != true)) {
                    this.PreAuthPriceField = value;
                    this.RaisePropertyChanged("PreAuthPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreAuthQueryID {
            get {
                return this.PreAuthQueryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PreAuthQueryIDField, value) != true)) {
                    this.PreAuthQueryIDField = value;
                    this.RaisePropertyChanged("PreAuthQueryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RealPreAuthPrice {
            get {
                return this.RealPreAuthPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.RealPreAuthPriceField, value) != true)) {
                    this.RealPreAuthPriceField = value;
                    this.RaisePropertyChanged("RealPreAuthPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentService.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/LogPayment", ReplyAction="http://tempuri.org/IPaymentService/LogPaymentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/LogPaymentReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        int LogPayment(string upWrapperBase64, string logType, string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/AddUPBindingCard", ReplyAction="http://tempuri.org/IPaymentService/AddUPBindingCardResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/AddUPBindingCardReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        int AddUPBindingCard(string cusWrapperBase64, string tokenBase64, string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetUserCreditCard", ReplyAction="http://tempuri.org/IPaymentService/GetUserCreditCardResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/GetUserCreditCardReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        CF.VRent.Entities.PaymentService.PaymentCard[] GetUserCreditCard(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/DeleteUPBindingCard", ReplyAction="http://tempuri.org/IPaymentService/DeleteUPBindingCardResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/DeleteUPBindingCardReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        int DeleteUPBindingCard(string id, string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetCardToken", ReplyAction="http://tempuri.org/IPaymentService/GetCardTokenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/GetCardTokenReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        string GetCardToken(string id, string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/AddPaymentMessageExchange", ReplyAction="http://tempuri.org/IPaymentService/AddPaymentMessageExchangeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/AddPaymentMessageExchangeReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        int AddPaymentMessageExchange(CF.VRent.Entities.PaymentService.PaymentExchangeMessage message, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetPaymentMessageState", ReplyAction="http://tempuri.org/IPaymentService/GetPaymentMessageStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/GetPaymentMessageStateReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        int GetPaymentMessageState(string Id, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/UpdatePaymentMessageExchange", ReplyAction="http://tempuri.org/IPaymentService/UpdatePaymentMessageExchangeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/UpdatePaymentMessageExchangeReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        int UpdatePaymentMessageExchange(CF.VRent.Entities.PaymentService.PaymentExchangeMessage message, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/UpdatePaymentMessageExchangeRetry", ReplyAction="http://tempuri.org/IPaymentService/UpdatePaymentMessageExchangeRetryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/UpdatePaymentMessageExchangeRetryReturnResultF" +
            "ault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        int UpdatePaymentMessageExchangeRetry(int paymentId, int retryFlag, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/UpdatePaymentMessageExchangeStatus", ReplyAction="http://tempuri.org/IPaymentService/UpdatePaymentMessageExchangeStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/UpdatePaymentMessageExchangeStatusReturnResult" +
            "Fault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        int UpdatePaymentMessageExchangeStatus(int paymentId, CF.VRent.UPSDK.PaymentStatusEnum paymentStatus, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetPaymentExchangeInfo", ReplyAction="http://tempuri.org/IPaymentService/GetPaymentExchangeInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/GetPaymentExchangeInfoReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        CF.VRent.Entities.PaymentService.PaymentExchangeMessage GetPaymentExchangeInfo(int Id, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetAllRetryBookings", ReplyAction="http://tempuri.org/IPaymentService/GetAllRetryBookingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/GetAllRetryBookingsReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        CF.VRent.Entities.PaymentService.RetryBooking[] GetAllRetryBookings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/UpdateCreditCardState", ReplyAction="http://tempuri.org/IPaymentService/UpdateCreditCardStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/UpdateCreditCardStateReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        int UpdateCreditCardState(string cardId, int state, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/UpdateBookingStatusAfterPayment", ReplyAction="http://tempuri.org/IPaymentService/UpdateBookingStatusAfterPaymentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/UpdateBookingStatusAfterPaymentReturnResultFau" +
            "lt", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        int UpdateBookingStatusAfterPayment(string kmId, string state, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetPaymentStatusByBookingId", ReplyAction="http://tempuri.org/IPaymentService/GetPaymentStatusByBookingIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/GetPaymentStatusByBookingIdReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        int GetPaymentStatusByBookingId(int bookingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/AddUPBindingCardViaUP", ReplyAction="http://tempuri.org/IPaymentService/AddUPBindingCardViaUPResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/AddUPBindingCardViaUPReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        string AddUPBindingCardViaUP(string customInfoJson, string reservedMsg, string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/CheckPaymentStatusViaUP", ReplyAction="http://tempuri.org/IPaymentService/CheckPaymentStatusViaUPResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/CheckPaymentStatusViaUPReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        CF.VRent.Common.Entities.ReturnResult CheckPaymentStatusViaUP(string resCode, int paymentId, string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/CancelCardBindingViaUP", ReplyAction="http://tempuri.org/IPaymentService/CancelCardBindingViaUPResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/CancelCardBindingViaUPReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        string CancelCardBindingViaUP(string token, string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/SendBindingSMSCodeViaUP", ReplyAction="http://tempuri.org/IPaymentService/SendBindingSMSCodeViaUPResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/SendBindingSMSCodeViaUPReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        string SendBindingSMSCodeViaUP(string cardObjectJson, string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/SendPreauthorizationSMSCodeViaUP", ReplyAction="http://tempuri.org/IPaymentService/SendPreauthorizationSMSCodeViaUPResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/SendPreauthorizationSMSCodeViaUPReturnResultFa" +
            "ult", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        string SendPreauthorizationSMSCodeViaUP(string cardObjectJson, string price, string uid, string tempOrderId, string tempOrderTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/CancelAndPreauthOnce", ReplyAction="http://tempuri.org/IPaymentService/CancelAndPreauthOnceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/CancelAndPreauthOnceReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        int CancelAndPreauthOnce(string price, string cardId, string smsCode, int paymentId, int bookingId, string bookingUserSetting, string tempOrderId, string tempOrderTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PreauthOnce", ReplyAction="http://tempuri.org/IPaymentService/PreauthOnceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/PreauthOnceReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        int PreauthOnce(string price, string cardId, string smsCode, string bookingUserSetting, int proxyBookingId, string tempOrderId, string tempOrderTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/CancelPreauthOnce", ReplyAction="http://tempuri.org/IPaymentService/CancelPreauthOnceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/CancelPreauthOnceReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        void CancelPreauthOnce(int paymentId, string price, string bookingUserSetting, int bookingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/DeductionOnce", ReplyAction="http://tempuri.org/IPaymentService/DeductionOnceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/DeductionOnceReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        void DeductionOnce(string type, string price, string cardId, int bookingId, int[] orderItemIds, string bookingUserSetting, string userSetting, string userPwd, string tempOrderId, string tempOrderTime, bool retry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/FinishAndDeduction", ReplyAction="http://tempuri.org/IPaymentService/FinishAndDeductionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/FinishAndDeductionReturnResultFault", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        void FinishAndDeduction(string type, double price, string kemasBookingId, int proxyBookingId, string bookingUserId, int paymentId, string cardId, string bookingUserSetting, string userSetting, string priceStructure, string userPwd, string tempOrderId, string tempOrderTime, string kemasState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetFailedTransactionByBooking", ReplyAction="http://tempuri.org/IPaymentService/GetFailedTransactionByBookingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/GetFailedTransactionByBookingReturnResultFault" +
            "", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        CF.VRent.Entities.PaymentService.PaymentExchangeMessage[] GetFailedTransactionByBooking(int bookingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/AddPaymentExchangeMessageHistory", ReplyAction="http://tempuri.org/IPaymentService/AddPaymentExchangeMessageHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CF.VRent.Common.Entities.ReturnResult), Action="http://tempuri.org/IPaymentService/AddPaymentExchangeMessageHistoryReturnResultFa" +
            "ult", Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.Common.Entities")]
        void AddPaymentExchangeMessageHistory(CF.VRent.Entities.PaymentService.PaymentExchangeMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : CF.VRent.Entities.PaymentService.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<CF.VRent.Entities.PaymentService.IPaymentService>, CF.VRent.Entities.PaymentService.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int LogPayment(string upWrapperBase64, string logType, string uid) {
            return base.Channel.LogPayment(upWrapperBase64, logType, uid);
        }
        
        public int AddUPBindingCard(string cusWrapperBase64, string tokenBase64, string uid) {
            return base.Channel.AddUPBindingCard(cusWrapperBase64, tokenBase64, uid);
        }
        
        public CF.VRent.Entities.PaymentService.PaymentCard[] GetUserCreditCard(string uid) {
            return base.Channel.GetUserCreditCard(uid);
        }
        
        public int DeleteUPBindingCard(string id, string uid) {
            return base.Channel.DeleteUPBindingCard(id, uid);
        }
        
        public string GetCardToken(string id, string uid) {
            return base.Channel.GetCardToken(id, uid);
        }
        
        public int AddPaymentMessageExchange(CF.VRent.Entities.PaymentService.PaymentExchangeMessage message, string userId) {
            return base.Channel.AddPaymentMessageExchange(message, userId);
        }
        
        public int GetPaymentMessageState(string Id, string userId) {
            return base.Channel.GetPaymentMessageState(Id, userId);
        }
        
        public int UpdatePaymentMessageExchange(CF.VRent.Entities.PaymentService.PaymentExchangeMessage message, string userId) {
            return base.Channel.UpdatePaymentMessageExchange(message, userId);
        }
        
        public int UpdatePaymentMessageExchangeRetry(int paymentId, int retryFlag, string userId) {
            return base.Channel.UpdatePaymentMessageExchangeRetry(paymentId, retryFlag, userId);
        }
        
        public int UpdatePaymentMessageExchangeStatus(int paymentId, CF.VRent.UPSDK.PaymentStatusEnum paymentStatus, string userId) {
            return base.Channel.UpdatePaymentMessageExchangeStatus(paymentId, paymentStatus, userId);
        }
        
        public CF.VRent.Entities.PaymentService.PaymentExchangeMessage GetPaymentExchangeInfo(int Id, string userId) {
            return base.Channel.GetPaymentExchangeInfo(Id, userId);
        }
        
        public CF.VRent.Entities.PaymentService.RetryBooking[] GetAllRetryBookings() {
            return base.Channel.GetAllRetryBookings();
        }
        
        public int UpdateCreditCardState(string cardId, int state, string userId) {
            return base.Channel.UpdateCreditCardState(cardId, state, userId);
        }
        
        public int UpdateBookingStatusAfterPayment(string kmId, string state, string userId) {
            return base.Channel.UpdateBookingStatusAfterPayment(kmId, state, userId);
        }
        
        public int GetPaymentStatusByBookingId(int bookingId) {
            return base.Channel.GetPaymentStatusByBookingId(bookingId);
        }
        
        public string AddUPBindingCardViaUP(string customInfoJson, string reservedMsg, string uid) {
            return base.Channel.AddUPBindingCardViaUP(customInfoJson, reservedMsg, uid);
        }
        
        public CF.VRent.Common.Entities.ReturnResult CheckPaymentStatusViaUP(string resCode, int paymentId, string uid) {
            return base.Channel.CheckPaymentStatusViaUP(resCode, paymentId, uid);
        }
        
        public string CancelCardBindingViaUP(string token, string uid) {
            return base.Channel.CancelCardBindingViaUP(token, uid);
        }
        
        public string SendBindingSMSCodeViaUP(string cardObjectJson, string uid) {
            return base.Channel.SendBindingSMSCodeViaUP(cardObjectJson, uid);
        }
        
        public string SendPreauthorizationSMSCodeViaUP(string cardObjectJson, string price, string uid, string tempOrderId, string tempOrderTime) {
            return base.Channel.SendPreauthorizationSMSCodeViaUP(cardObjectJson, price, uid, tempOrderId, tempOrderTime);
        }
        
        public int CancelAndPreauthOnce(string price, string cardId, string smsCode, int paymentId, int bookingId, string bookingUserSetting, string tempOrderId, string tempOrderTime) {
            return base.Channel.CancelAndPreauthOnce(price, cardId, smsCode, paymentId, bookingId, bookingUserSetting, tempOrderId, tempOrderTime);
        }
        
        public int PreauthOnce(string price, string cardId, string smsCode, string bookingUserSetting, int proxyBookingId, string tempOrderId, string tempOrderTime) {
            return base.Channel.PreauthOnce(price, cardId, smsCode, bookingUserSetting, proxyBookingId, tempOrderId, tempOrderTime);
        }
        
        public void CancelPreauthOnce(int paymentId, string price, string bookingUserSetting, int bookingId) {
            base.Channel.CancelPreauthOnce(paymentId, price, bookingUserSetting, bookingId);
        }
        
        public void DeductionOnce(string type, string price, string cardId, int bookingId, int[] orderItemIds, string bookingUserSetting, string userSetting, string userPwd, string tempOrderId, string tempOrderTime, bool retry) {
            base.Channel.DeductionOnce(type, price, cardId, bookingId, orderItemIds, bookingUserSetting, userSetting, userPwd, tempOrderId, tempOrderTime, retry);
        }
        
        public void FinishAndDeduction(string type, double price, string kemasBookingId, int proxyBookingId, string bookingUserId, int paymentId, string cardId, string bookingUserSetting, string userSetting, string priceStructure, string userPwd, string tempOrderId, string tempOrderTime, string kemasState) {
            base.Channel.FinishAndDeduction(type, price, kemasBookingId, proxyBookingId, bookingUserId, paymentId, cardId, bookingUserSetting, userSetting, priceStructure, userPwd, tempOrderId, tempOrderTime, kemasState);
        }
        
        public CF.VRent.Entities.PaymentService.PaymentExchangeMessage[] GetFailedTransactionByBooking(int bookingId) {
            return base.Channel.GetFailedTransactionByBooking(bookingId);
        }
        
        public void AddPaymentExchangeMessageHistory(CF.VRent.Entities.PaymentService.PaymentExchangeMessage message) {
            base.Channel.AddPaymentExchangeMessageHistory(message);
        }
    }
}
