//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CF.VRent.Entities.FapiaoPreferenceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProxyFapiaoPreference", Namespace="http://schemas.datacontract.org/2004/07/CF.VRent.DataAccessProxy.Entities")]
    [System.SerializableAttribute()]
    public partial class ProxyFapiaoPreference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddresseeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FapiaoTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddresseeName {
            get {
                return this.AddresseeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AddresseeNameField, value) != true)) {
                    this.AddresseeNameField = value;
                    this.RaisePropertyChanged("AddresseeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FapiaoType {
            get {
                return this.FapiaoTypeField;
            }
            set {
                if ((this.FapiaoTypeField.Equals(value) != true)) {
                    this.FapiaoTypeField = value;
                    this.RaisePropertyChanged("FapiaoType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailAddress {
            get {
                return this.MailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.MailAddressField, value) != true)) {
                    this.MailAddressField = value;
                    this.RaisePropertyChanged("MailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailPhone {
            get {
                return this.MailPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MailPhoneField, value) != true)) {
                    this.MailPhoneField = value;
                    this.RaisePropertyChanged("MailPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailType {
            get {
                return this.MailTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MailTypeField, value) != true)) {
                    this.MailTypeField = value;
                    this.RaisePropertyChanged("MailType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((this.ModifiedByField.Equals(value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedOn {
            get {
                return this.ModifiedOnField;
            }
            set {
                if ((this.ModifiedOnField.Equals(value) != true)) {
                    this.ModifiedOnField = value;
                    this.RaisePropertyChanged("ModifiedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FapiaoPreferenceProxy.IFapiaoPreferenceService")]
    public interface IFapiaoPreferenceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFapiaoPreferenceService/GetAllFapiaoPreference", ReplyAction="http://tempuri.org/IFapiaoPreferenceService/GetAllFapiaoPreferenceResponse")]
        CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference[] GetAllFapiaoPreference(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFapiaoPreferenceService/GetFapiaoPreferenceDetail", ReplyAction="http://tempuri.org/IFapiaoPreferenceService/GetFapiaoPreferenceDetailResponse")]
        CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference GetFapiaoPreferenceDetail(string fpid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFapiaoPreferenceService/CreateFapiaoPreference", ReplyAction="http://tempuri.org/IFapiaoPreferenceService/CreateFapiaoPreferenceResponse")]
        CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference CreateFapiaoPreference(CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference fp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFapiaoPreferenceService/DeleteFapiaoPreference", ReplyAction="http://tempuri.org/IFapiaoPreferenceService/DeleteFapiaoPreferenceResponse")]
        void DeleteFapiaoPreference(string fpid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFapiaoPreferenceService/UpdateFapiaoPreference", ReplyAction="http://tempuri.org/IFapiaoPreferenceService/UpdateFapiaoPreferenceResponse")]
        CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference UpdateFapiaoPreference(CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference oldfp, CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference newFP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFapiaoPreferenceServiceChannel : CF.VRent.Entities.FapiaoPreferenceProxy.IFapiaoPreferenceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FapiaoPreferenceServiceClient : System.ServiceModel.ClientBase<CF.VRent.Entities.FapiaoPreferenceProxy.IFapiaoPreferenceService>, CF.VRent.Entities.FapiaoPreferenceProxy.IFapiaoPreferenceService {
        
        public FapiaoPreferenceServiceClient() {
        }
        
        public FapiaoPreferenceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FapiaoPreferenceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FapiaoPreferenceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FapiaoPreferenceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference[] GetAllFapiaoPreference(string uid) {
            return base.Channel.GetAllFapiaoPreference(uid);
        }
        
        public CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference GetFapiaoPreferenceDetail(string fpid) {
            return base.Channel.GetFapiaoPreferenceDetail(fpid);
        }
        
        public CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference CreateFapiaoPreference(CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference fp) {
            return base.Channel.CreateFapiaoPreference(fp);
        }
        
        public void DeleteFapiaoPreference(string fpid) {
            base.Channel.DeleteFapiaoPreference(fpid);
        }
        
        public CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference UpdateFapiaoPreference(CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference oldfp, CF.VRent.Entities.FapiaoPreferenceProxy.ProxyFapiaoPreference newFP) {
            return base.Channel.UpdateFapiaoPreference(oldfp, newFP);
        }
    }
}
