//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CF.VRent.SAPSDK.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigureFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigureFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CF.VRent.SAPSDK.Configuration.ConfigureFiles", typeof(ConfigureFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;CompanyCode&gt;
        ///  &lt;Branch name=&quot;Beijing&quot; code=&quot;4073&quot;&gt;
        ///    &lt;Corporate&gt;FC00&lt;/Corporate&gt;
        ///    &lt;Private&gt;PC00&lt;/Private&gt;
        ///  &lt;/Branch&gt;
        ///  &lt;Branch name=&quot;Dalian&quot; code=&quot;4081&quot;&gt;
        ///    &lt;Corporate&gt;FC00&lt;/Corporate&gt;
        ///    &lt;Private&gt;PC00&lt;/Private&gt;
        ///  &lt;/Branch&gt;
        ///&lt;/CompanyCode&gt;
        ///&lt;!--&lt;Clients&gt;
        ///  &lt;Client&gt;
        ///    &lt;Branch&gt;Beijing&lt;/Branch&gt;
        ///    &lt;BranchCHE&gt;&lt;/BranchCHE&gt;
        ///    &lt;CompanyCode&gt;4073&lt;/CompanyCode&gt;
        ///    &lt;BusinessAreaCode&gt;00&lt;/BusinessAreaCode&gt;
        ///    &lt;State&gt;1&lt;/State&gt;
        ///    &lt;ClientName&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAP_FI_CompanyCode {
            get {
                return ResourceManager.GetString("SAP_FI_CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Settings&gt;
        ///  &lt;Setting name=&quot;RemoteSharedFolder&quot; value=&quot;\\172.21.216.21\Test2&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;LocalMapDeviceName&quot; value=&quot;X:&quot;&gt;&lt;/Setting&gt;
        ///  &lt;Setting name=&quot;RemoteUserName&quot; value=&quot;condali\al250545&quot;&gt;&lt;/Setting&gt;
        ///  &lt;Setting name=&quot;RemoteUserPassword&quot; value=&quot;2jSpIoYV&quot;&gt;&lt;/Setting&gt;
        ///  &lt;Setting name=&quot;FileExtension&quot; value=&quot;.CSV&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;DateFormat&quot; value=&quot;yyyyMMdd&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;FieldDelimiter&quot; value=&quot;|&quot;&gt;
        ///  &lt;/Setting&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAP_FI_Posting_Common {
            get {
                return ResourceManager.GetString("SAP_FI_Posting_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Settings&gt;
        ///  &lt;Setting name=&quot;Country&quot; value=&quot;CN&quot; order=&quot;1&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;ClientInTargetSystem&quot; value=&quot;126&quot; order=&quot;2&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;CompanyCode&quot; value=&quot;4070&quot; order=&quot;3&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;Module&quot; value=&quot;FI-&quot; order=&quot;4&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;ShortName&quot; value=&quot;GLDOC&quot; order=&quot;5&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;SendingSystem&quot; value=&quot;CLM&quot; order=&quot;6&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;ConstantValue&quot; value=&quot;-I&quot; order= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAP_FI_Posting_FileName {
            get {
                return ResourceManager.GetString("SAP_FI_Posting_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Settings&gt;
        ///  &lt;Setting name=&quot;Sign&quot; value=&quot;1&quot; order=&quot;1&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;CompanyCode&quot; value=&quot;4070&quot; order=&quot;2&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;Currency&quot; value=&quot;CNY&quot; order=&quot;3&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;DocumentType&quot; value=&quot;IE&quot; order=&quot;4&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;PostingDate&quot; value=&quot;&quot; order=&quot;5&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;DocumentDate&quot; value=&quot;&quot; order=&quot;6&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;Reference&quot; value=&quot;(Header Reference)&quot; order=&quot;7&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAP_FI_Posting_Header {
            get {
                return ResourceManager.GetString("SAP_FI_Posting_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Settings&gt;
        ///  &lt;Setting name=&quot;Sign&quot; value=&quot;2&quot; order=&quot;1&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;DebitOrCredit&quot; value=&quot;D&quot; order=&quot;2&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;KindOfAccount&quot; value=&quot;G&quot; order=&quot;3&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;Account&quot; value=&quot;0199201254&quot; order=&quot;4&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;Amount&quot; value=&quot;&quot; order=&quot;5&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;AmountInForeignCurrency&quot; value=&quot;&quot; order=&quot;6&quot;&gt;
        ///  &lt;/Setting&gt;
        ///  &lt;Setting name=&quot;BaselineDate&quot; value=&quot;&quot; order=&quot;7&quot;&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAP_FI_Posting_Item {
            get {
                return ResourceManager.GetString("SAP_FI_Posting_Item", resourceCulture);
            }
        }
    }
}
