CREATE TABLE [dbo].[CompletedBookings] (
    [ID]                 INT              IDENTITY (1, 1) NOT NULL,
    [KemasBookingID]     UNIQUEIDENTIFIER NOT NULL,
    [BookingID]          INT              NULL,
    [DateBegin]          DATETIME         NOT NULL,
    [DateEnd]            DATETIME         NOT NULL,
    [StartLocationID]    UNIQUEIDENTIFIER NOT NULL,
    [StartLocationName]  NVARCHAR (50)    NOT NULL,
    [BillingOption]      TINYINT          NOT NULL,
    [Category]           NVARCHAR (20)    NOT NULL,
    [CreatorID]          UNIQUEIDENTIFIER NOT NULL,
    [UserID]             UNIQUEIDENTIFIER NOT NULL,
    [CorporateID]        UNIQUEIDENTIFIER NOT NULL,
    [CorporateName]      NVARCHAR (50)    NOT NULL,
    [CarID]              UNIQUEIDENTIFIER NULL,
    [CarName]            NVARCHAR (50)    NOT NULL,
    [KemasBookingNumber] NVARCHAR (20)    NOT NULL,
    [PickupBegin]        DATETIME         NULL,
    [PickupEnd]          DATETIME         NULL,
    [KeyOut]             DATETIME         NULL,
    [KeyIn]              DATETIME         NULL,
    [State]              NVARCHAR (50)    NOT NULL,
    [Price]              DECIMAL (10, 3)  NOT NULL,
    [PricingDetail]      NVARCHAR (MAX)   NULL,
    [PaymentStatus]      NVARCHAR (20)    NULL,
    [SyncState]          TINYINT          NOT NULL,
    [MatchState]         TINYINT          NOT NULL,
    [CreatedOn]          DATETIME         NOT NULL,
    [CreatedBy]          UNIQUEIDENTIFIER NOT NULL,
    [ModifiedOn]         DATETIME         NULL,
    [ModifiedBy]         UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_CompletedBookings] PRIMARY KEY CLUSTERED ([ID] ASC)
);

