CREATE TABLE [dbo].[FapiaoData] (
    [ID]                    INT              IDENTITY (1, 1) NOT NULL,
    [ItemID]                INT              NOT NULL,
    [UniqueID]              NVARCHAR (20)    NULL,
    [DealNumber]            NVARCHAR (20)    NULL,
    [ContractNumber]        NVARCHAR (20)    NULL,
    [CustomerID]            NVARCHAR (20)    NOT NULL,
    [CustomerName]          NVARCHAR (20)    NULL,
    [TaxID]                 NVARCHAR (20)    NULL,
    [CustomerAddress]       NVARCHAR (120)   NULL,
    [CustomerPhone]         NVARCHAR (20)    NULL,
    [BankName]              NVARCHAR (80)    NULL,
    [BankAccount]           NVARCHAR (80)    NULL,
    [FPCustomerName]        NVARCHAR (20)    NULL,
    [FPMailType]            NVARCHAR (80)    NULL,
    [FPMailAddress]         NVARCHAR (80)    NULL,
    [FPMailPhone]           NVARCHAR (20)    NULL,
    [FPAddresseeName]       NVARCHAR (50)    NULL,
    [ProductCode]           NVARCHAR (20)    NULL,
    [Spec_Mode]             NVARCHAR (20)    NULL,
    [UnitMeasure]           NVARCHAR (10)    NULL,
    [SalesQuantity]         NUMERIC (3)      NULL,
    [UnitPrice]             NUMERIC (14, 2)  NULL,
    [NetAmount]             NUMERIC (14, 2)  NULL,
    [TaxRate]               NUMERIC (5, 4)   NULL,
    [Tax]                   NUMERIC (14, 2)  NULL,
    [TotalAmount]           NUMERIC (14, 2)  NULL,
    [FapiaoType]            NUMERIC (3)      NULL,
    [Remark]                NVARCHAR (230)   NULL,
    [GeneratedFapiaoNumber] NVARCHAR (20)    NULL,
    [GeneratedFapiaoCode]   NVARCHAR (20)    NULL,
    [FapiaoIssueDate]       DATETIME         NULL,
    [DeliverID]             NVARCHAR (100)   NULL,
    [State]                 TINYINT          NOT NULL,
    [CreatedOn]             DATETIME         NOT NULL,
    [CreatedBy]             UNIQUEIDENTIFIER NOT NULL,
    [ModifiedOn]            DATETIME         NULL,
    [ModifiedBy]            UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_FapiaoData] PRIMARY KEY CLUSTERED ([ID] ASC)
);

