CREATE TABLE [dbo].[VrentCountry] (
    [COUNTRY_KEY] INT            IDENTITY (1, 1) NOT NULL,
    [ISO_CODE_2]  NVARCHAR (5)   NOT NULL,
    [ISO_CODE_3]  NVARCHAR (5)   NULL,
    [EN_NAME]     NVARCHAR (200) NOT NULL,
    [DE_NAME]     NVARCHAR (200) NULL,
    [CN_NAME]     NVARCHAR (200) NULL,
    CONSTRAINT [PK_DIM_COUNTRY] PRIMARY KEY CLUSTERED ([COUNTRY_KEY] ASC)
);

